"""
solution.py – DocFusion challenge entry point.

Handles two JSONL schemas:
  Schema A (real data):       {"id":..., "ocr_lines":[...], "is_forged":0}
  Schema B (dummy/structured):{"id":..., "fields":{...}, "label":{"is_forged":0}}

CORD integration:
  If data/cord/ exists (generated by tools/prepare_cord.py), CORD records are
  automatically merged into training as additional genuine samples.
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.pipeline import load_jsonl, run_pipeline
from src.anomaly.train_detector import train_detector

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
)
logger = logging.getLogger("DocFusionSolution")

# ── CORD config ───────────────────────────────────────────────────────────────
# Path to CORD JSONL files produced by tools/prepare_cord.py.
# Override by setting the CORD_DIR environment variable.
import os
_DEFAULT_CORD_DIR = PROJECT_ROOT / "data" / "cord"
CORD_DIR = Path(os.environ.get("CORD_DIR", _DEFAULT_CORD_DIR))

# Maximum number of CORD samples to add (None = all).
# Keep this reasonable to avoid blowing up memory on the judge machine.
CORD_MAX_SAMPLES = int(os.environ.get("CORD_MAX_SAMPLES", "3000"))


def _parse_record_for_training(rec: dict) -> dict:
    """
    Normalise a training record regardless of which schema it uses.
    Returns a flat dict: id, text, vendor, date, total, is_forged
    """
    doc_id = rec["id"]

    # ── Label ────────────────────────────────────────────────────────────────
    if "is_forged" in rec:
        is_forged = int(rec["is_forged"])
    elif "label" in rec and isinstance(rec["label"], dict):
        is_forged = int(rec["label"].get("is_forged", 0))
    else:
        is_forged = 0

    # ── Fields ───────────────────────────────────────────────────────────────
    pre_fields = rec.get("fields") or {}
    vendor = pre_fields.get("vendor") or rec.get("vendor")
    date   = pre_fields.get("date")   or rec.get("date")
    total  = pre_fields.get("total")  or rec.get("total")

    # ── Text ─────────────────────────────────────────────────────────────────
    ocr_lines = rec.get("ocr_lines", [])
    if not isinstance(ocr_lines, list):
        ocr_lines = []

    if ocr_lines:
        text = "\n".join(str(x) for x in ocr_lines if x is not None)
    else:
        parts = []
        if vendor: parts.append(f"vendor {vendor}")
        if date:   parts.append(f"date {date}")
        if total:  parts.append(f"total {total}")
        text = " ".join(parts)

    return {
        "id":        doc_id,
        "text":      text,
        "vendor":    vendor,
        "date":      date,
        "total":     total,
        "is_forged": is_forged,
    }


def _load_cord_records(cord_dir: Path, max_samples: int | None) -> list[dict]:
    """Load CORD JSONL files from cord_dir. Returns [] if not found."""
    if not cord_dir.exists():
        return []

    records = []
    # Load train split first, then validation
    for fname in ["cord_train.jsonl", "cord_validation.jsonl"]:
        fpath = cord_dir / fname
        if not fpath.exists():
            continue
        for rec in load_jsonl(fpath):
            records.append(rec)
            if max_samples and len(records) >= max_samples:
                return records

    return records


class DocFusionSolution:

    # -------------------------------------------------------------------------
    def train(self, train_dir: str, work_dir: str) -> str:
        train_dir = Path(train_dir)
        work_dir  = Path(work_dir)
        model_dir   = work_dir / "docfusion_model"
        anomaly_dir = model_dir / "anomaly"
        anomaly_dir.mkdir(parents=True, exist_ok=True)

        train_jsonl = train_dir / "train.jsonl"
        logger.info("Loading training data from %s", train_jsonl)

        records = load_jsonl(train_jsonl)
        logger.info("Loaded %d competition training records", len(records))

        # ── Augment with CORD genuine receipts ────────────────────────────────
        cord_records = _load_cord_records(CORD_DIR, CORD_MAX_SAMPLES)
        if cord_records:
            records.extend(cord_records)
            logger.info(
                "Augmented with %d CORD genuine records (total: %d)",
                len(cord_records), len(records),
            )
        else:
            logger.info(
                "No CORD data found at %s. "
                "Run tools/prepare_cord.py to generate it.",
                CORD_DIR,
            )

        rows = [_parse_record_for_training(r) for r in records]
        train_df = pd.DataFrame(rows)

        n_forged  = int((train_df["is_forged"] == 1).sum())
        n_genuine = int((train_df["is_forged"] == 0).sum())
        logger.info("Final training set: %d genuine, %d forged", n_genuine, n_forged)

        train_detector(train_df, anomaly_dir)
        logger.info("Training complete. Model saved to %s", model_dir)

        return str(model_dir)

    # -------------------------------------------------------------------------
    def predict(self, model_dir: str, data_dir: str, out_path: str) -> None:
        model_dir = Path(model_dir)
        data_dir  = Path(data_dir)
        out_path  = Path(out_path)

        test_jsonl = data_dir / "test.jsonl"
        images_dir = data_dir / "images"

        logger.info("Loading test data from %s", test_jsonl)
        records = load_jsonl(test_jsonl)
        logger.info("Running pipeline on %d records…", len(records))

        predictions = run_pipeline(model_dir, records, images_dir)

        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            for row in predictions:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")

        logger.info("Wrote %d predictions to %s", len(predictions), out_path)